const Application = require('../module/application');
const HrEmail = require('../module/hrEmail');
const Job = require('../module/job');
const User = require('../module/user');
const mongoose = require('mongoose');
const transporter = require('../config/email');

exports.applyJob = async (req, res) => {
  try {
    const { jobId, experience, coverLetter, selectedHr } = req.body;
    const studentId = req.user.id;
    const resumeFile = req.file;

    if (!jobId || !experience || !coverLetter) {
      return res.status(400).json({ success: false, message: "All fields are required" });
    }
    if (!resumeFile) {
      return res.status(400).json({ success: false, message: "Resume file is required" });
    }
    if (!mongoose.Types.ObjectId.isValid(jobId)) {
      return res.status(400).json({ success: false, message: "Invalid Job ID" });
    }

    const job = await Job.findById(jobId);
    if (!job) return res.status(404).json({ success: false, message: "Job not found" });

    const alreadyApplied = await Application.findOne({ studentId, jobId });
    if (alreadyApplied) return res.status(400).json({ success: false, message: "You already applied for this job" });

    const student = await User.findById(studentId).select("-password");
    if (!student) return res.status(404).json({ success: false, message: "Student not found" });

    // Save application — store just the filename
    await Application.create({
      studentId,
      jobId,
      experience,
      coverLetter,
      selectedHr,
      resume: resumeFile.originalname,
    });

    const hrEmails = await HrEmail.find({ jobId });

    if (hrEmails.length > 0) {
      await Promise.all(
        hrEmails.map((hr) =>
          transporter.sendMail({
            from: `"Job Portal" <${process.env.EMAIL_USER}>`,
            to: hr.email,
            replyTo: student.email,  // HR replies → goes directly to student
            cc: student.email,
            subject: `Application for ${job.title} — ${student.username}`,

            // ✅ PDF attached directly to email — no links, no Cloudinary
            attachments: [
              {
                filename: resumeFile.originalname,
                content: resumeFile.buffer,
                contentType: resumeFile.mimetype,
              },
            ],

html: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
</head>
<body style="margin:0;padding:0;font-family:Arial, sans-serif; background:#ffffff; color:#000000;">

  <div style="max-width:600px;margin:30px auto;padding:20px;border:1px solid #dddddd;">

    <h2 style="margin-bottom:20px;">New Job Application</h2>

    <p><strong>Position:</strong> ${job.title}</p>
    ${job.location ? `<p><strong>Location:</strong> ${job.location}</p>` : ""}

    <hr style="margin:20px 0;" />

    <h3>Candidate Details</h3>

    <p><strong>Name:</strong> ${student.username}</p>
    <p><strong>Email:</strong> 
      <a href="mailto:${student.email}">${student.email}</a>
    </p>
    <p><strong>Experience:</strong> ${experience}</p>

    <hr style="margin:20px 0;" />

    <h3>Cover Letter</h3>
    <p style="white-space:pre-line; line-height:1.6;">
      ${coverLetter}
    </p>

    <hr style="margin:20px 0;" />

    <p><strong>Resume:</strong> ${resumeFile.originalname}</p>
    <p>The resume is attached to this email.</p>

    <br/>

    <p style="font-size:12px;">
      This email was automatically generated by the Job Portal system.
      <br/>
      You can reply directly to contact the candidate.
    </p>

  </div>

</body>
</html>
`
          })
        )
      );
    }

    return res.status(201).json({ success: true, message: "Application submitted successfully" });

  } catch (error) {
    console.error("Apply Job Error:", error);
    return res.status(500).json({ success: false, message: "Something went wrong while applying" });
  }
};


exports.getMyApplications = async (req, res) => {
  try {
    const studentId = req.user.id;
    const applications = await Application.find({ studentId }).select("jobId").lean();
    res.status(200).json({ success: true, applications });
  } catch (error) {
    res.status(500).json({ success: false, message: "Failed to fetch applications" });
  }
};


exports.getAllApplications = async (req, res) => {
  try {
    const applications = await Application.find()
      .populate("studentId", "username email")
      .populate("jobId", "title location")
      .sort({ createdAt: -1 });
    res.status(200).json({ success: true, applications });
  } catch (error) {
    res.status(500).json({ success: false, message: "Failed to fetch applications" });
  }
};